[package]
name = "deb-version"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]

[dev-dependencies]
apt-pkg-native = "0.2.0"
lazy_static = "0.2.8"
quickcheck = "0.4.1"
regex = "0.2.2"
